import CodansCore
import CodansIPC
import Foundation

/// A handoff that finished through the CLI handler, announced so the in-app
/// Hand Off panel waiting on an injected request can correlate it with its
/// source pane and finish.
nonisolated struct HandoffCompletion: Equatable, Sendable {
  let action: IPC.HandoffAction
  let sourcePaneID: PaneID
  let receiver: AgentKind?
  let briefing: HandoffBriefingOutcome
  let launched: IPC.HandoffLaunchedPane?
  /// Id generated by the panel, or nil for an ordinary CLI handoff.
  let requestID: UUID?
}

/// Owns the one-shot authorization for a panel-injected handoff request and
/// fans out CLI completions to whoever is waiting on them. The panel and the
/// socket handler both run on the main actor, so claiming a request or
/// superseding it for a fallback is one serialised state transition — the
/// two paths can never both perform the transition.
@MainActor
final class HandoffRequestRegistry {
  private enum State {
    case pending
    case claimed
    case superseded
  }

  private var states: [UUID: State] = [:]
  private var subscribers: [UUID: AsyncStream<HandoffCompletion>.Continuation] = [:]

  init() {}

  func register(_ requestID: UUID) {
    states[requestID] = .pending
  }

  /// Claims a pending request for its CLI transition. A request is claimed
  /// at most once and cannot run after a fallback superseded it.
  @discardableResult
  func claim(_ requestID: UUID) -> Bool {
    guard states[requestID] == .pending else { return false }
    states[requestID] = .claimed
    return true
  }

  /// Supersedes a still-pending request before the panel starts its own
  /// context-only transition. A handler that already claimed it owns the
  /// transition and must be allowed to finish instead.
  @discardableResult
  func supersede(_ requestID: UUID) -> Bool {
    guard states[requestID] == .pending else { return false }
    states[requestID] = .superseded
    return true
  }

  /// Every completion from now on. Broadcast, no replay: subscribe before
  /// injecting the request so the answer cannot be missed.
  func completions() -> AsyncStream<HandoffCompletion> {
    let id = UUID()
    return AsyncStream { continuation in
      subscribers[id] = continuation
      continuation.onTermination = { [weak self] _ in
        Task { @MainActor in self?.subscribers.removeValue(forKey: id) }
      }
    }
  }

  func publish(_ completion: HandoffCompletion) {
    for continuation in subscribers.values {
      continuation.yield(completion)
    }
  }
}
